version: "3"
services:
  geocloud_nmea:
    image: innovationgarage/geocloud_nmea:latest
    environment:
      CONFIG: |
        {
            "connections": [
                {"handler": "source", "type": "listen", "address": "tcp:1024"},
                {"handler": "source", "type": "connect", "address": "tcp:153.44.253.27:5631"},
                {"handler": "destination", "type": "listen", "address": "tcp:1025"}
            ]
        }    
    ports:
      - "6024:1024"
      - "6025:1025"
